var CountryCodeList = [
    {"code": "US", "name": "United States", "flag": "🇺🇸"},
    {"code": "CA", "name": "Canada", "flag": "🇨🇦"},
    {"code": "GB", "name": "United Kingdom", "flag": "🇬🇧"},
    {"code": "DE", "name": "Germany", "flag": "🇩🇪"},
    {"code": "FR", "name": "France", "flag": "🇫🇷"},
    {"code": "IN", "name": "India", "flag": "🇮🇳"},
    {"code": "CN", "name": "China", "flag": "🇨🇳"},
    {"code": "JP", "name": "Japan", "flag": "🇯🇵"},
    {"code": "BR", "name": "Brazil", "flag": "🇧🇷"},
    {"code": "AU", "name": "Australia", "flag": "🇦🇺"},
    {"code": "RU", "name": "Russia", "flag": "🇷🇺"},
    {"code": "IT", "name": "Italy", "flag": "🇮🇹"},
    {"code": "ES", "name": "Spain", "flag": "🇪🇸"},
    {"code": "MX", "name": "Mexico", "flag": "🇲🇽"},
    {"code": "KR", "name": "South Korea", "flag": "🇰🇷"},
    {"code": "SA", "name": "Saudi Arabia", "flag": "🇸🇦"},
    {"code": "ZA", "name": "South Africa", "flag": "🇿🇦"},
    {"code": "AR", "name": "Argentina", "flag": "🇦🇷"},
    {"code": "EG", "name": "Egypt", "flag": "🇪🇬"},
    {"code": "NG", "name": "Nigeria", "flag": "🇳🇬"},
    {"code": "SE", "name": "Sweden", "flag": "🇸🇪"},
    {"code": "NL", "name": "Netherlands", "flag": "🇳🇱"},
    {"code": "CH", "name": "Switzerland", "flag": "🇨🇭"},
    {"code": "BE", "name": "Belgium", "flag": "🇧🇪"},
    {"code": "AT", "name": "Austria", "flag": "🇦🇹"},
    {"code": "NO", "name": "Norway", "flag": "🇳🇴"},
    {"code": "DK", "name": "Denmark", "flag": "🇩🇰"},
    {"code": "FI", "name": "Finland", "flag": "🇫🇮"},
    {"code": "PL", "name": "Poland", "flag": "🇵🇱"},
    {"code": "PT", "name": "Portugal", "flag": "🇵🇹"},
    {"code": "GR", "name": "Greece", "flag": "🇬🇷"},
    {"code": "HU", "name": "Hungary", "flag": "🇭🇺"},
    {"code": "CZ", "name": "Czech Republic", "flag": "🇨🇿"},
    {"code": "IE", "name": "Ireland", "flag": "🇮🇪"},
    {"code": "NZ", "name": "New Zealand", "flag": "🇳🇿"},
    {"code": "SG", "name": "Singapore", "flag": "🇸🇬"},
    {"code": "MY", "name": "Malaysia", "flag": "🇲🇾"},
    {"code": "TH", "name": "Thailand", "flag": "🇹🇭"},
    {"code": "ID", "name": "Indonesia", "flag": "🇮🇩"},
    {"code": "PH", "name": "Philippines", "flag": "🇵🇭"},
    {"code": "VN", "name": "Vietnam", "flag": "🇻🇳"},
    {"code": "IL", "name": "Israel", "flag": "🇮🇱"},
    {"code": "TR", "name": "Turkey", "flag": "🇹🇷"},
    {"code": "IR", "name": "Iran", "flag": "🇮🇷"},
    {"code": "PK", "name": "Pakistan", "flag": "🇵🇰"},
    {"code": "BD", "name": "Bangladesh", "flag": "🇧🇩"},
    {"code": "KE", "name": "Kenya", "flag": "🇰🇪"},
    {"code": "GH", "name": "Ghana", "flag": "🇬🇭"},
    {"code": "UG", "name": "Uganda", "flag": "🇺🇬"}
  ]
  